baseURL = 'https://344blog.4thavenue.info'
languageCode = 'ja'
title = '34feed'
theme = 'hugo-theme-stack'

[params]
  author = "さしし@sasisi344"
  description = "自分のインプットをアウトプットする感じの雑記ブログです。"
  keywords = ["tech", "programming", "ai", "machine learning"]
  mainSections = ["tech", "blog", "news"]

[params.Author]
  name = "さしし@sasisi344"
  email = "sasisi344@gmail.com"
  
[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "記事"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    name = "アーカイブ"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    name = "タグ"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "検索"
    url = "/search/"
    weight = 5
