baseURL = 'https://344blog.4thavenue.info'
languageCode = 'ja'
title = '34feed'
theme = 'hugo-theme-stack'

# サイトマップ設定を追加
[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "さしし@sasisi344"
  description = "自分のインプットをアウトプットする感じの雑記ブログです。"
  keywords = ["tech", "programming", "ai", "machine learning"]
  mainSections = ["Jurnal", "Tech", "Local"]

[params.Author]
  name = "さしし@sasisi344"
  email = "sasisi344@gmail.com"
  
[[menu.social]]
  identifier = "twitter"
  name = "twitter"
  url = "https://x.com/sasisi344"
  weight = 10
    [menu.social.params]
    icon = "brand-twitter"
    newTab = true

 [[menu.social]]
  identifier = "instagram"
  name = "Instagram"
  url = "https://www.instagram.com/sasisi344/"
  weight = 15
    [menu.social.params]
    icon = "brand-instagram"   # ← assets/icons/brand-instagram.svg と一致
    newTab = true

 [[menu.social]]
  identifier = "threads"
  name = "Threads"
  url = "https://www.threads.net/@sasisi344"
  weight = 20
    [menu.social.params]
    icon = "brand-threads" 
    newTab = true

  [[menu.social]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = 30
    [menu.social.params]
    icon = "rss"